version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: plena_postgres
    environment:
      POSTGRES_USER: plena_user
      POSTGRES_PASSWORD: plena_password
      POSTGRES_DB: plena_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
